"""Stage A abstract result simulation.

The package is intentionally independent from ``simulation.race_engine``.  It
uses validated content models as input, then owns its own immutable snapshot,
logical clock, random streams, performance model and result objects.
"""

from .clock import LogicalClock
from .broadcast import (
    AbstractBroadcastSession,
    AbstractBroadcastSessionManager,
    abstract_broadcast_session_manager,
)
from .engine import AbstractRaceEngine, run_abstract_qualifying, run_abstract_race
from .race import AbstractTrafficSimulationCursor, AbstractTrafficTick
from .incidents import (
    ContactAssessment,
    LockupAssessment,
    assess_contact,
    assess_lockup,
)
from .performance import (
    PERFORMANCE_AXES,
    SegmentRequirement,
    SegmentTimeBreakdown,
    VehiclePerformance,
    calculate_segment_time,
    segment_time,
)
from .pose import (
    AbstractPoseFrame,
    PoseSynthesizer,
    SingleProbeKinematicCursor,
    SingleProbeKinematicTick,
    SingleVehiclePoseSynthesizer,
    TrackSpline,
    TrackSplineSample,
)
from .kinematics import (
    BoundedKinematicPoseBuffer,
    CompiledSplineArcLengthAdapter,
    KinematicPoseBuffer,
    KINEMATIC_LOGICAL_TICK_SECONDS,
    KINEMATICS_PLAN_VERSION,
    LateralTrajectory,
    LongitudinalKinematicPlan,
    RacingLineDistanceContract,
    SpeedKnot,
    build_longitudinal_plan,
    pose_sequence_hash,
)
from .qualifying import QualifyingEngine
from .pit import PitStopPlan, build_pit_plans
from .progress_race import (
    DEFAULT_PROGRESS_TICK_SECONDS,
    PROGRESS_RACE_ENGINE_VERSION,
    PROGRESS_RACECRAFT_AUTHORITY_VERSION,
    PROGRESS_RACE_RESULT_CONTRACT,
    PROGRESS_TIMING_AUTHORITY_VERSION,
    ProgressFinishResult,
    ProgressRaceCursor,
    ProgressRuntimeCheckpoint,
    ProgressRaceSummary,
    ProgressRaceTick,
    ProgressVehicleState,
    run_progress_race,
)
from .progress_broadcast import (
    PROGRESS_BROADCAST_PRESENTATION_CONTRACT,
    ProgressBroadcastCursor,
    ProgressBroadcastRuntimeCheckpoint,
)
from .replay import InterruptibleReplayClock, LogicalReplayCursor, RollingFrameBuffer
from .racecraft import (
    TrafficCorridorReservation,
    LocalCorridorAssessment,
    OvertakeAssessment,
    audit_accepted_frame_reservations,
    audit_reservation_intersections,
    assess_overtake,
    corridor_required_width_m,
    local_corridor_assessment,
)
from simulation.track_display import TrackDisplayGeometry, build_track_display_geometry
from .rng import (
    IndependentRNG,
    RNGStream,
    derive_stream_seed,
    stream_name,
)
from .state import (
    AbstractCommandRecord,
    AbstractDriverProfile,
    AbstractEntrySnapshot,
    AbstractEnvironmentSnapshot,
    AbstractQualifyingResult,
    AbstractRaceFrame,
    AbstractRaceResult,
    AbstractSessionSnapshot,
    AbstractTrackSnapshot,
    AbstractVehicleSnapshot,
    AbstractTimingCheckpoint,
    DriverQualifyingResult,
    GridEntry,
    LogicalEvent,
    QualifyingRunResult,
    QualifyingSessionSummary,
    RaceVehicleState,
    SectorRequirement,
    TireConditionSnapshot,
)

__all__ = [
    "AbstractDriverProfile",
    "AbstractCommandRecord",
    "AbstractBroadcastSession",
    "AbstractBroadcastSessionManager",
    "AbstractEntrySnapshot",
    "AbstractEnvironmentSnapshot",
    "AbstractPoseFrame",
    "AbstractQualifyingResult",
    "AbstractRaceEngine",
    "AbstractRaceFrame",
    "AbstractRaceResult",
    "AbstractTrafficSimulationCursor",
    "AbstractTrafficTick",
    "AbstractSessionSnapshot",
    "AbstractTimingCheckpoint",
    "AbstractTrackSnapshot",
    "AbstractVehicleSnapshot",
    "ContactAssessment",
    "DriverQualifyingResult",
    "GridEntry",
    "IndependentRNG",
    "LogicalClock",
    "LogicalEvent",
    "LockupAssessment",
    "PERFORMANCE_AXES",
    "PoseSynthesizer",
    "PROGRESS_RACE_ENGINE_VERSION",
    "PROGRESS_RACE_RESULT_CONTRACT",
    "DEFAULT_PROGRESS_TICK_SECONDS",
    "PitStopPlan",
    "QualifyingEngine",
    "RollingFrameBuffer",
    "LogicalReplayCursor",
    "InterruptibleReplayClock",
    "QualifyingRunResult",
    "QualifyingSessionSummary",
    "ProgressFinishResult",
    "ProgressRaceCursor",
    "ProgressBroadcastCursor",
    "ProgressBroadcastRuntimeCheckpoint",
    "PROGRESS_BROADCAST_PRESENTATION_CONTRACT",
    "ProgressRuntimeCheckpoint",
    "ProgressRaceSummary",
    "ProgressRaceTick",
    "ProgressVehicleState",
    "RaceVehicleState",
    "RNGStream",
    "SectorRequirement",
    "SegmentRequirement",
    "SegmentTimeBreakdown",
    "SingleVehiclePoseSynthesizer",
    "SingleProbeKinematicCursor",
    "SingleProbeKinematicTick",
    "TireConditionSnapshot",
    "TrackSpline",
    "TrackSplineSample",
    "BoundedKinematicPoseBuffer",
    "CompiledSplineArcLengthAdapter",
    "KinematicPoseBuffer",
    "KINEMATIC_LOGICAL_TICK_SECONDS",
    "KINEMATICS_PLAN_VERSION",
    "LateralTrajectory",
    "LongitudinalKinematicPlan",
    "RacingLineDistanceContract",
    "SpeedKnot",
    "build_longitudinal_plan",
    "pose_sequence_hash",
    "TrackDisplayGeometry",
    "OvertakeAssessment",
    "TrafficCorridorReservation",
    "LocalCorridorAssessment",
    "audit_accepted_frame_reservations",
    "audit_reservation_intersections",
    "assess_overtake",
    "assess_contact",
    "assess_lockup",
    "abstract_broadcast_session_manager",
    "build_pit_plans",
    "build_track_display_geometry",
    "corridor_required_width_m",
    "local_corridor_assessment",
    "VehiclePerformance",
    "calculate_segment_time",
    "derive_stream_seed",
    "run_abstract_qualifying",
    "run_abstract_race",
    "run_progress_race",
    "segment_time",
    "stream_name",
]
